### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-AnaAmaro#1]
Really cool job @AnaAmaro !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Menu items should be clickable
- [x] The child of a UL can only be an LI, not a DIV

## CSS - box model
- [x] Instead of adding extra space at the bottom of the header, you can make the menu links taller, that would make the header be tall enough and also would make the link easier to touch on mobile devices ;)
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] Do not use "menu-item2". We prefer to use "menu-item contact"

## Assets
- [x] Use relative routes

## Good practices
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Muy buen trabajo en general, sigue así Ana!!!

**Comment by AnaAmaro** [comment]
Corregido :)

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
